# Generated by Django 5.1.3 on 2024-12-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asmeb3610',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPS', models.CharField(max_length=10)),
                ('DN', models.CharField(max_length=10)),
                ('Sch', models.CharField(max_length=10)),
                ('OD', models.CharField(max_length=10)),
                ('Thk', models.CharField(max_length=10)),
                ('Weight', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Asmeb3619',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPS', models.CharField(max_length=10)),
                ('DN', models.CharField(max_length=10)),
                ('Sch', models.CharField(max_length=10)),
                ('OD', models.CharField(max_length=10)),
                ('Thk', models.CharField(max_length=10)),
                ('Weight', models.CharField(max_length=10)),
            ],
        ),
    ]
